# Generated by Django 3.2.5 on 2021-07-17 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcshopp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('descriptions', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('videomemory', models.CharField(max_length=255, verbose_name='Объём видеопамяти')),
                ('frequency', models.CharField(max_length=255, verbose_name='Частота')),
                ('videomemory_type', models.CharField(max_length=255, verbose_name='Тип видеопамяти')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcshopp.category', verbose_name='Категории')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('descriptions', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('volume', models.CharField(max_length=255, verbose_name='Объём памяти')),
                ('frequency', models.CharField(max_length=255, verbose_name='Частота')),
                ('voltage', models.CharField(max_length=255, verbose_name='Напряжение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcshopp.category', verbose_name='Категории')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Powersupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('descriptions', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('power', models.CharField(max_length=255, verbose_name='Мощность')),
                ('fansize', models.CharField(max_length=255, verbose_name='Размер вентилятора')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcshopp.category', verbose_name='Категории')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('descriptions', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('socket', models.CharField(max_length=255, verbose_name='Сокет')),
                ('chipset', models.CharField(max_length=255, verbose_name='Чипсет')),
                ('memory_type', models.CharField(max_length=255, verbose_name='Тип памяти')),
                ('slot', models.CharField(max_length=255, verbose_name='Слоты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcshopp.category', verbose_name='Категории')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('descriptions', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('socket', models.CharField(max_length=255, verbose_name='Сокет')),
                ('frequency', models.CharField(max_length=255, verbose_name='Частота')),
                ('core', models.CharField(max_length=255, verbose_name='Колличество ядер')),
                ('technicalprocess', models.CharField(max_length=255, verbose_name='Техпроцесс')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcshopp.category', verbose_name='Категории')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
