# Generated by Django 3.2.5 on 2021-07-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcshopp', '0002_cpu_motherboard_powersupply_ram_videocard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
