# Generated by Django 3.2.4 on 2021-07-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcshopp', '0004_auto_20210720_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testmm',
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pcshopp.customer', verbose_name='Владелец'),
        ),
    ]
